## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("/Users/michaelmanthey/Documents/Bootcamp/Module_6_Python_APIs/Challenge/Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description,Hotel Name
0,2,Faanui,-16.4833,-151.7500,78.96,66,6,14.14,clear sky,Bora-Bora Pearl Beach Resort & Spa
1,13,Port Blair,11.6667,92.7500,77.04,88,75,13.80,broken clouds,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
2,15,Butaritari,3.0707,172.7902,81.75,77,30,7.83,light rain,Isles Sunset Lodge
3,16,Acapulco,16.8634,-99.8901,85.82,74,40,8.05,scattered clouds,HS Hotsson Smart Acapulco
4,21,Jacareacanga,-6.2222,-57.7528,85.03,34,100,1.43,overcast clouds,Casa do IanðŸ˜Ž

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
<dt>Weather Description</dt><dd>{Description}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [42]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [87]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["Hotel Name"] == "Sea Lounge! Bar, Club & Restaurant")]
vacation_end = vacation_df.loc[(vacation_df["Hotel Name"] == "Hotel Albergue de Olinda")]
vacation_stop1 = vacation_df.loc[(vacation_df["Hotel Name"] == "Romin")]
vacation_stop2 = vacation_df.loc[(vacation_df["Hotel Name"] == "INN NEW HORIZON")]
vacation_stop3 = vacation_df.loc[(vacation_df["Hotel Name"] == "Villa Park Hotel | Natal")]
vacation_start

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description,Hotel Name
92,331,Itarema,-2.9248,-39.9167,79.0,81,6,15.39,clear sky,"Sea Lounge! Bar, Club & Restaurant"

In [151]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start[["Lat", "Lng"]]).to_records(index=False)
start1 = tuple(start)
true_start = start1[0]

end = (vacation_end[["Lat", "Lng"]]).to_records(index=False)
end1 = tuple(end)
true_end = end1[0]

stop1 = (vacation_stop1[["Lat", "Lng"]]).to_records(index=False)
stop1_1 = tuple(stop1)
true_stop1 = stop1_1[0]

stop2 = (vacation_stop2[["Lat", "Lng"]]).to_records(index=False)
stop2_1 = tuple(stop2)
true_stop2 = stop2_1[0]

stop3 = (vacation_stop3[["Lat", "Lng"]]).to_records(index=False)
stop3_1 = tuple(stop3)
true_stop3 = stop3_1[0]

waypoints = true_stop1, true_stop2, true_stop3

#create itinerary df
route = [vacation_start, vacation_end, vacation_stop1, vacation_stop2, vacation_stop3]
itinerary_df = pd.concat(route,ignore_index=True)
itinerary_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description,Hotel Name
0,331,Itarema,-2.9248,-39.9167,79.00,81,6,15.39,clear sky,"Sea Lounge! Bar, Club & Restaurant"
1,498,Olinda,-8.0089,-34.8553,76.73,78,40,5.75,scattered clouds,Hotel Albergue de Olinda
2,376,Papara,-3.9839,-38.7273,79.20,95,58,4.32,broken clouds,Romin
3,325,Touros,-5.1989,-35.4608,76.10,79,3,14.14,clear sky,INN NEW HORIZON
4,129,Natal,-5.7950,-35.2094,77.22,83,20,8.05,few clouds,Villa Park Hotel | Natal

In [160]:
info_box_template1 = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
<dt>Description</dt><dd>{Description}</dd>
</dl>
"""
route_info = [info_box_template1.format(**row) for index, row in itinerary_df.iterrows()]

# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure(center=(-5.0, -36.0), zoom_level=5.0)
locations = true_start, true_end, true_stop1, true_stop2, true_stop3
directions_layer = gmaps.directions_layer(start=true_start,
                                          end=true_end,
                                          waypoints=waypoints,
                                          avoid_ferries=False,
                                          travel_mode="DRIVING",
                                          avoid_highways=False,
                                          avoid_tolls=False,
                                          optimize_waypoints=False,
                                          show_markers=False,
                                          show_route=True,
                                          stroke_color="#0088FF",
                                          stroke_weight=6.0,
                                          stroke_opacity=0.6)
marker_layer = gmaps.marker_layer(locations, info_box_content=route_info, display_info_box=True)
fig.add_layer(marker_layer)
fig.add_layer(directions_layer)

fig

Figure(layout=FigureLayout(height='420px'))